baseURL = 'https://jrgn.org'
languageCode = 'en-us'
title = "j__r0d's garage network"
author = "j__r0d"
copyright = "© 2022 jrgn.org"
googleAnalytics = "G-CNQE23ECH5"

publishDir = "W:\\"

# ----- Site settings -----
theme = "risotto"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main" # Automatically add content sections to main menu
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser.attribute]
block = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# -----.Site.Params-----
[params]
noindex = false
source = "https://github.com/jr0dsgarage/jrgn.org"

[params.theme]
palette = "base16-dark-custom"

[params.about] # to be used only in about section of Sidebar
title = "jrgn.org"
description = "The online presence for j__r0d’s garage network, a personal homelab"
logo = "avatars/BRZ (125x125).jpg"

# -----Sidebar: menu items-----
[menu] # Customize specific menu items
  [[menu.main]]
    identifier = "a2"
    name = "Apple II"
    url = "/a2/"

# -----Sidebar: social links-----
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')
[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/jr0dsgarage"

[[params.socialLinks]]
icon = "fa-brands fa-mastodon"
title = "Mastadon"
url = "https://mastodon.social/@j__r0d#"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:jrods.mailbox@gmail.com"

# -----Privacy Settings-----
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
  [privacy.mastodon]
    disable = false
    privacyEnhanced = false

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
